### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by Keno** [symengine/SymEngine.jl#174] opened 2019-08-17 22:20 UTC
I'm probably not using this package right, but it'd be nice to get a nice error rather than a segfault:

```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.708 (2018-11-22)
 _/ |\__'_|_|_|\__'_|  |  Commit 038d866* (268 days old master)
|__/                   |

julia> using SymEngine

julia> x = symbols("x")
x

julia> coeff(5x^4, x^4)

signal (11): Segmentation fault: 11
in expression starting at no file:0
_ZN9SymEngine9julia_strERKNS_5BasicE at /Users/kfischer/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.0.4.0.dylib (unknown line)
basic_str_julia at /Users/kfischer/.julia/packages/SymEngine/zSUGO/deps/libsymengine-0.4/lib/libsymengine.0.4.0.dylib (unknown line)
```

**Comment by isuruf** [comment] 2019-08-17 22:30
I'll mark this as a duplicate of https://github.com/symengine/SymEngine.jl/issues/80
`libsymengine` gives an error code, but SymEngine.jl ignores it.

Btw, correct invocation is `coeff(5x^4, x, 4)`. I don't know why that is different from `coeff(5x^4, x^4, 1)`

**Closed** 2020-03-16 20:32 UTC
