### ISSUE TITLE
Specifying Derivatives

### ISSUE THREAD

**Issue by ChrisRackauckas** [symengine/SymEngine.jl#81] opened 2017-04-13 17:32 UTC
I see that the derivative functionality is heavily increased! Using ParameterizedFunctions (which uses SymEngine in it), the differential equation

```julia
println("Test difficult differentiable")
NJ = @ode_def_nohes DiffDiff begin
  dx = a*x - b*x*y
  dy = -c*y + erf(x*y/d)
end a=>1.5 b=>1 c=3 d=4
```

is able to accurately build its Jacobian:

```julia
println(NJ.Jex)
# output
begin 
    J[1,1] = p.a - p.b * u[2]
    J[1,2] = -(p.b) * u[1]
    J[2,1] = ((1 / 2) * u[2] * E ^ ((-1 / 16) * u[1] ^ 2 * u[2] ^ 2)) / sqrt(pi)
    J[2,2] = -3 + ((1 / 2) * u[1] * E ^ ((-1 / 16) * u[1] ^ 2 * u[2] ^ 2)) / sqrt(pi)
    nothing
end
```

The Julia function it creates (has that body, with the signature `(t,u,J)` doesn't currently work, but that sounds like it will be solved by https://github.com/symengine/symengine/issues/1225. Wondering how far this new derivative engine goes, I tested what happens when I wrap something in a function:

```julia
test_fail(x,y,d) = erf(x*y/d)
println("Test non-differentiable")
NJ = @ode_def NoJacTest begin
  dx = a*x - b*x*y
  dy = -c*y + test_fail(x,y,d)
end a=>1.5 b=>1 c=3 d=4
NJ(t,u,du)
@test du == [-3.0;-3*3.0 + erf(2.0*3.0/4)]
@test du == NJ(t,u)
```

and it gives

```julia
println(NJ.Jex)
# output
begin 
    J[1,1] = p.a - p.b * u[2]
    J[1,2] = -(p.b) * u[1]
    J[2,1] = Derivative(test_fail(u[1],u[2],4),u[1])
    J[2,2] = -3 + Derivative(test_fail(u[1],u[2],4),u[2])
    nothing
end
```

This derivative is unknown, but now it looks like a function? How do we overload that `Derivative` function? It would be nice to document that, and I'll pass my users onto those docs.

**Comment by isuruf** [comment] 2017-05-10 07:29
Duplicate of #53

**Closed by isuruf** 2017-05-10 07:29 UTC
