### ISSUE TITLE
Operation on Complex Numbers

### ISSUE THREAD

**Issue by timkittel** [symengine/SymEngine.jl#123] opened 2018-07-18 12:49 UTC
Hi,
I am trying to use `SymEngine` with complex numbers but somehow I am not really managing to get started. Something I am wondering about is: In the following, should the second line either result simply in `a` (if `a` and be are assumed to be real from the beginning) or something like `real(a) - imag(b)` (if they are assumed to be complex from the beginngin). Is there a special way to treat complex numbers in `SymEngine`?
```Julia
julia> @vars a b
(a, b)

julia> a + im*b |> real
a + I*b
```
Thank you,
Tim

**Comment by isuruf** [comment] 2018-07-18 20:07
Duplicate of https://github.com/symengine/SymEngine.jl/issues/110

**Closed by isuruf** 2018-07-18 20:07 UTC
